/** Offline word bank — English + compact Urdu/Roman banks. */
import { EXTENDED_WORDS } from "./extendedWords.ts";

const RAW: Record<string, string> = {
  animals:
    "DOG CAT LION TIGER BEAR WOLF FOX DEER HORSE ZEBRA PANDA KOALA CAMEL GOAT SHEEP MOUSE RABBIT WHALE SHARK EAGLE HAWK OWL FROG SNAKE LIZARD MONKEY GORILLA CHEETAH LEOPARD JAGUAR HYENA JACKAL OTTER BEAVER BADGER MOOSE BISON LLAMA ALPACA SLOTH LEMUR WOMBAT DINGO COYOTE PUPPY KITTEN KITTEN CUB PUP FOAL CALF LAMB KID PONY MARE STALLION BULL COW OX PIG BOAR HOG RAM EWE STAG DOE HARE SQUIRREL CHIPMUNK RACCOON SKUNK PORCUPINE ARMADILLO AARDVARK ANTELOPE GAZELLE IMPALA WILDEBEEST GIRAFFE ELEPHANT RHINO HIPPO WALRUS SEAL DOLPHIN PORPOISE NARWHAL ORCA MANATEE PLATYPUS WOMBAT FERRET WEASEL MINK STOAT MARTEN LYNX BOBCAT COUGAR PUMA PANTHER CIVET GENET MEERKAT MONGOOSE BABOON GIBBON ORANGUTAN CHIMP BONOBO MACAQUE TAMARIN MARMOSET TAPIR PECCARY CAPYBARA AGOUTI PACA COATI KINKAJOU OPOSSUM WOMBAT NUTRIA VOLE SHREW MOLE BAT",
  birds:
    "CROW RAVEN ROBIN SPARROW FINCH WREN SWAN DUCK GOOSE HERON STORK CRANE EGRET IBIS PELICAN GULL TERN PUFFIN PENGUIN ALBATROSS PETREL FALCON KITE OSPREY BUZZARD VULTURE CONDOR PARROT MACAW COCKATOO PARAKEET LORIKEET TOUCAN HORNBILL KINGFISHER BEEATER WOODPECKER CUCKOO DOVE PIGEON QUAIL PHEASANT GROUSE TURKEY PEACOCK PEAHEN HEN ROOSTER CHICK MAGPIE JAY STARLING BLACKBIRD THRUSH WARBLER LARK SWIFT SWALLOW MARTIN NIGHTINGALE CANARY CARDINAL BLUEJAY ORIOLE TANAGER WAXWING DIPPER GREBE LOON CORMORANT GANNET BOOBY FRIGATE SKUA JAEGER AUK MURRE GUILLEMOT DOVEKIE KESTREL MERLIN GYRFALCON HARRIER SPARROWHAWK GOSHAWK",
  fruits:
    "APPLE MANGO GRAPE PEACH PEAR PLUM CHERRY BERRY LEMON LIME ORANGE MELON PAPAYA GUAVA KIWI FIG DATE OLIVE BANANA COCONUT LYCHEE LONGAN RAMBUTAN DURIAN JACKFRUIT POMELO CITRON TANGELO APRICOT NECTARINE QUINCE PERSIMMON POMEGRANATE BLUEBERRY RASPBERRY BLACKBERRY STRAWBERRY CRANBERRY GOOSEBERRY MULBERRY ELDERBERRY BOYSENBERRY LOGANBERRY CLOUDBERRY LINGONBERRY CURRANT RAISIN SULTANA PRUNE AVOCADO TOMATO PASSION STARFRUIT DRAGONFRUIT SOURSOP CUSTARD WATERMELON CANTALOUPE HONEYDEW PITAYA ACEROLA JUJUBE LOQUAT MEDLAR SAPODILLA TAMARIND",
  vegetables:
    "CARROT ONION GARLIC GINGER POTATO TOMATO CABBAGE LETTUCE SPINACH CELERY PEPPER CHILI RADISH TURNIP BEETROOT BEET PARSNIP YAM TARO CASSAVA OKRA BEANS PEAS LENTIL CHICKPEA SOYBEAN BROCCOLI CAULIFLOWER KALE CHARD ROCKET ARUGULA ENDIVE FENNEL LEEK SHALLOT SCALLION SQUASH PUMPKIN ZUCCHINI CUCUMBER GOURD EGGPLANT AUBERGINE CORN MAIZE RICE WHEAT BARLEY OATS MILLET SORGHUM QUINOA BUCKWHEAT ARTICHOKE ASPARAGUS BRUSSELS KOHLRABI RUTABAGA JICAMA DAIKON WASABI HORSERADISH MUSTARD CRESS WATERCRESS NETTLE SORREL RHUBARB",
  countries:
    "PAKISTAN INDIA CHINA JAPAN KOREA NEPAL BHUTAN BANGLADESH SRILANKA AFGHANISTAN IRAN IRAQ TURKEY EGYPT SUDAN KENYA NIGERIA GHANA MOROCCO ALGERIA TUNISIA LIBYA SPAIN FRANCE ITALY GERMANY POLAND SWEDEN NORWAY DENMARK FINLAND GREECE PORTUGAL IRELAND ENGLAND SCOTLAND WALES BRAZIL MEXICO CANADA CUBA PERU CHILE ARGENTINA COLOMBIA VENEZUELA ECUADOR BOLIVIA URUGUAY PARAGUAY PANAMA JAMAICA HAITI BELIZE HONDURAS NICARAGUA AUSTRALIA FIJI SAMOA TONGA RUSSIA UKRAINE BELARUS GEORGIA ARMENIA AZERBAIJAN KAZAKHSTAN UZBEKISTAN TAJIKISTAN KYRGYZSTAN TURKMENISTAN MONGOLIA VIETNAM THAILAND MALAYSIA SINGAPORE INDONESIA PHILIPPINES MYANMAR CAMBODIA LAOS BRUNEI QATAR KUWAIT BAHRAIN OMAN YEMEN JORDAN LEBANON SYRIA ISRAEL PALESTINE CYPRUS MALTA ICELAND ESTONIA LATVIA LITHUANIA HUNGARY ROMANIA BULGARIA SERBIA CROATIA SLOVENIA SLOVAKIA AUSTRIA SWISS BELGIUM HOLLAND",
  cities:
    "KARACHI LAHORE ISLAMABAD PESHAWAR QUETTA MULTAN FAISALABAD RAWALPINDI HYDERABAD SUKKUR LARKANA SIALKOT GUJRANWALA DELHI MUMBAI KOLKATA CHENNAI BANGALORE DHAKA KABUL TEHRAN BAGHDAD ISTANBUL ANKARA CAIRO RIYADH DUBAI DOHA MUSCAT AMMAN BEIRUT DAMASCUS JERUSALEM LONDON PARIS ROME MADRID BERLIN VIENNA PRAGUE WARSAW MOSCOW KYIV ATHENS LISBON DUBLIN OSLO STOCKHOLM HELSINKI COPENHAGEN AMSTERDAM BRUSSELS ZURICH GENEVA MILAN NAPLES VENICE FLORENCE BARCELONA VALENCIA SEVILLE PORTO TOKYO OSAKA KYOTO SEOUL BUSAN BEIJING SHANGHAI SHENZHEN GUANGZHOU HONGKONG TAIPEI BANGKOK HANOI SAIGON JAKARTA MANILA KUALA SINGAPORE SYDNEY MELBOURNE PERTH AUCKLAND WELLINGTON NEWYORK BOSTON CHICAGO MIAMI SEATTLE DENVER DALLAS HOUSTON ATLANTA TORONTO VANCOUVER MONTREAL MEXICO LIMA BOGOTA QUITO SANTIAGO BUENOS CAPETOWN NAIROBI LAGOS ACCRA TUNIS ALGIERS CASABLANCA RABAT TRIPOLI ADDIS",
  sports:
    "CRICKET FOOTBALL HOCKEY TENNIS SQUASH BOXING KARATE JUDO CHESS POLO GOLF RUGBY BASEBALL SOFTBALL BASKETBALL VOLLEYBALL HANDBALL NETBALL BADMINTON TABLETENNIS PINGPONG SWIMMING DIVING SURFING SAILING ROWING CANOE KAYAK CYCLING RUNNING SPRINT MARATHON RELAY HURDLE JUMP THROW JAVELIN DISCUS HAMMER SHOTPUT WRESTLING FENCING ARCHERY SHOOTING CLIMBING SKIING SNOWBOARD SKATING HOCKEYPUCK CURLING BOWLING BILLIARDS SNOOKER DARTS YOGA PILATES AEROBICS GYMNASTICS TRAMPOLINE WEIGHTLIFTING POWERLIFTING CROSSFIT PARKOUR SKATEBOARD ROLLERBLADING EQUESTRIAN DRESSAGE POLOMATCH LACROSSE WATERPOLO SYNCHRO TRIATHLON PENTATHLON DECATHLON",
  professions:
    "DOCTOR NURSE TEACHER PILOT CHEF BAKER DRIVER JUDGE LAWYER FARMER MINER SAILOR SOLDIER POLICE FIREMAN GUARD BANKER TELLER CLERK WRITER POET ARTIST ACTOR SINGER DANCER MUSICIAN PAINTER SCULPTOR DESIGNER ENGINEER BUILDER CARPENTER PLUMBER ELECTRICIAN MASON TAILOR WEAVER POTTER SMITH BUTCHER GROCER TRADER MERCHANT BROKER AGENT GUIDE RANGER SCIENTIST CHEMIST PHYSICIST BIOLOGIST GEOLOGIST ASTRONOMER MATHEMATICIAN HISTORIAN LIBRARIAN JOURNALIST EDITOR REPORTER PHOTOGRAPHER CAMERAMAN DIRECTOR PRODUCER ARCHITECT SURVEYOR ACCOUNTANT AUDITOR CASHIER MANAGER DIRECTOR MAYOR MINISTER PRESIDENT AMBASSADOR DIPLOMAT TRANSLATOR INTERPRETER THERAPIST DENTIST SURGEON PHARMACIST VET PARAMEDIC LIFEGUARD COACH TRAINER REFEREE UMPIRE CAPTAIN SKIPPER MECHANIC TECHNICIAN PROGRAMMER ANALYST HACKER",
  technology:
    "COMPUTER LAPTOP TABLET PHONE SCREEN KEYBOARD MOUSE PRINTER CAMERA ROBOT DRONE SERVER CLOUD DATA CODE PIXEL BYTE BIT CHIP CIRCUIT SENSOR MODEM ROUTER CABLE WIRE NETWORK WIFI BLUETOOTH SATELLITE ANTENNA RADAR SONAR LASER OPTIC FIBER QUANTUM BINARY LOGIC ALGORITHM SOFTWARE HARDWARE FIRMWARE DATABASE QUERY CACHE BUFFER MEMORY STORAGE DISK DRIVE FOLDER FILE ICON APP WEBSITE BROWSER ENGINE SEARCH LOGIN TOKEN ENCRYPT HASH PASSWORD FIREWALL VIRUS MALWARE PATCH UPDATE VERSION RELEASE DEBUG COMPILE SCRIPT MODULE LIBRARY FRAMEWORK FRONTEND BACKEND CLIENT API JSON XML HTML CSS PYTHON JAVA RUST GOLANG SWIFT KOTLIN SCALA RUBY PERL SHELL LINUX UNIX WINDOWS ANDROID IPHONE PIXELATED VIRTUAL REALITY AUGMENTED MACHINE LEARNING NEURAL MODEL PROMPT TOKENIZE",
  space:
    "SUN MOON STAR EARTH MARS VENUS MERCURY JUPITER SATURN URANUS NEPTUNE PLUTO COMET METEOR ASTEROID GALAXY NEBULA PULSAR QUASAR SUPERNOVA BLACKHOLE ORBIT PLANET SATELLITE ROCKET SHUTTLE CAPSULE MODULE LANDER ROVER PROBE TELESCOPE OBSERVATORY ASTRONAUT COSMONAUT GRAVITY VACUUM COSMOS UNIVERSE MILKYWAY ANDROMEDA ORION PLEIADES POLARIS SIRIUS VEGA ALTAIR RIGEL BETELGEUSE ANTARES ALDEBARAN CAPELLA PROCYON DENEB SPICA REGULUS ARCTURUS ECLIPSE SOLAR LUNAR AURORA MAGNETOSPHERE IONOSPHERE STRATOSPHERE TROPOSPHERE ATMOSPHERE CRATER MARE HIGHLAND RIDGE CANYON DUST STARDUST COSMIC RAY PHOTON ELECTRON PROTON NEUTRON ATOM NUCLEUS FUSION FISSION PLASMA HELIUM HYDROGEN OXYGEN CARBON SILICON IRON NICKEL ICE RING TITAN EUROPA IO GANYMEDE CALLISTO PHOBOS DEIMOS TRITON CHARON CERES VESTA PALLAS HYGEIA",
  ocean:
    "OCEAN SEA WAVE TIDE CURRENT REEF CORAL ATOLL LAGOON BAY GULF STRAIT CHANNEL Fjord SOUND INLET COVE BEACH SHORE COAST CLIFF DUNE SAND PEBBLE SHELL PEARL KELP WEED ALGAE PLANKTON KRILL JELLYFISH STARFISH SEAHORSE CLOWNFISH TUNA SALMON COD TROUT BASS SNAPPER GROUPER MACKEREL SARDINE ANCHOVY HERRING EEL RAY SKATE FLOUNDER HALIBUT SWORDFISH MARLIN SAILFISH BARRACUDA PIRANHA CATFISH CARP KOI GOLDFISH BETTA GUPPY TETRA DISCUS ANGELFISH PUFFER LIONFISH STONEFISH MORAY OCTOPUS SQUID CUTTLEFISH NAUTILUS CRAB LOBSTER SHRIMP PRAWN CRAYFISH KRILL BARNACLE MUSSEL OYSTER CLAM SCALLOP WHELK CONCH ABALONE URCHIN ANEMONE SPONGE POLYPS WHIRLPOOL TSUNAMI TYPHOON CYCLONE HURRICANE SQUALL BREEZE GALE STORM SURF SPRAY FOAM DEPTH ABYSS TRENCH RIDGE SEAMOUNT GUYOT",
  body:
    "HEAD FACE EYE EAR NOSE MOUTH LIP TOOTH TONGUE CHIN JAW CHEEK BROW HAIR SKULL BRAIN NECK THROAT CHEST HEART LUNG LIVER KIDNEY STOMACH SPINE RIB ARM HAND PALM FINGER THUMB NAIL WRIST ELBOW SHOULDER BACK WAIST HIP LEG KNEE ANKLE FOOT TOE HEEL SOLE SKIN BONE MUSCLE NERVE BLOOD VEIN ARTERY PULSE CELL TISSUE ORGAN GLAND SPLEEN PANCREAS GALL BLADDER INTESTINE COLON RECTUM BLADDER UTERUS OVARY TESTIS PROSTATE THYROID TONSIL ADENOID SINUS CORNEA RETINA IRIS PUPIL LENS EARDRUM COCHLEA",
  emotions:
    "JOY LOVE HOPE CALM PEACE PRIDE TRUST FAITH GRACE MERCY KIND WARM GLOW SMILE LAUGH CHEER BLISS HAPPY GLAD MERRY JOLLY SUNNY SERENE QUIET STILL GENTLE SOFT SWEET TENDER CARING BRAVE BOLD STRONG FIERCE PROUD NOBLE LOYAL TRUE FAIR JUST WISE SMART SHARP QUICK ALERT AWAKE ALIVE EAGER KEEN READY OPEN FREE LIGHT BRIGHT CLEAR PURE FRESH CLEAN NEW YOUNG OLD WISE SAD TEAR CRY PAIN FEAR ANGER RAGE FURY SPITE ENVY GREED SHAME GUILT DOUBT WORRY STRESS ANXIETY PANIC DREAD GLOOM GRIEF LOSS HURT ACHE WOUND SCAR HEAL MEND GROW RISE SHINE GLOW BLOOM",
  food:
    "BREAD RICE WHEAT FLOUR SUGAR SALT SPICE HERB OIL BUTTER CHEESE CREAM MILK YOGURT HONEY JAM SYRUP SOUP STEW CURRY BIRYANI KEBAB TIKKA KORMA NIHARI HALEEM SAAG DAL NAAN ROTI PARATHA PULAO PILAF PASTA PIZZA BURGER SANDWICH TACO SUSHI RAMEN NOODLE DUMPLING SPRINGROLL SAMOSA PAKORA BHATOORA CHAPLI SEEKH KOFTA KEBAB ROLL WRAP SALAD PICKLE CHUTNEY RAITA LASSI CHAI COFFEE COCOA COCOA TEA JUICE WATER SODA SHAKE SMOOTHIE CAKE PIE TART COOKIE BISCUIT PASTRY DONUT MUFFIN BROWNIE PUDDING CUSTARD KHEER HALWA JALEBI GULAB JAMUN BARFI LADDU RASGULLA KULFI ICECREAM SORBET GELATO CHOCOLATE CANDY TOFFEE CARAMEL FUDGE NOUGAT MARSHMALLOW POPCORN PRETZEL CRACKER CHIP FRIES NACHOS QUESADILLA ENCHILADA PAELLA RISOTTO LASAGNA RAVIOLI GNOCCHI BRUSCHETTA TAPAS MEZE FALAFEL HUMMUS TABBOULEH SHAWARMA DONER GYRO",
  colors:
    "RED BLUE GREEN YELLOW ORANGE PURPLE VIOLET INDIGO PINK BROWN BLACK WHITE GRAY GREY GOLD SILVER BRONZE COPPER TEAL CYAN MAGENTA MAROON NAVY OLIVE LIME CORAL SALMON PEACH CREAM IVORY BEIGE TAN KHAKI AMBER RUBY EMERALD SAPPHIRE TOPAZ OPAL PEARL JET ONYX EBONY IVORY CRIMSON SCARLET VERMILION CARMINE ROSE FUCHSIA LILAC LAVENDER MAUVE PLUM ORCHID MAGENTA AZURE CERULEAN COBALT SAPPHIRE TURQUOISE AQUAMARINE MINT SAGE FOREST JADE OLIVE CHARTREUSE MUSTARD SAFFRON OCHRE SIENNA UMBER RUST BRICK TERRA COTTA",
  weather:
    "RAIN SNOW HAIL SLEET STORM WIND GALE BREEZE GUST SQUALL THUNDER LIGHTNING CLOUD FOG MIST HAZE SMOG SUNSHINE GLARE HEAT COLD CHILL FROST ICE THAW FLOOD DROUGHT HUMID ARID DRY WET DAMP MOIST WARM COOL HOT MILD FAIR CLEAR OVERCAST DRIZZLE SHOWER DOWNPOUR DELUGE MONSOON TYPHOON CYCLONE HURRICANE TORNADO TWISTER BLIZZARD WHITEOUT FLURRY FLAKE DROPLET PUDDLE RAINBOW AURORA HALO CORONA SUNDOG MOONDOG DEW FROST ICE RAIME GLAZE SLEET HAILSTONE THUNDERHEAD CUMULUS STRATUS CIRRUS NIMBUS ANVIL FUNNEL VORTEX PRESSURE FRONT TROUGH RIDGE JETSTREAM TRADEWIND WESTERLY EASTERLY NORTHERN SOUTHERN",
  islamic:
    "EID HAJJ SAWM ZAKAT IMAN DEEN MASJID QIBLA IFTAR SUHOOR TASBIH SALAH FAJR ZUHR ASR MAGHRIB ISHA JUMMAH WITR TAHAJJUD DUA DHIKR TAWBA SABR SHUKR TAQWA IHSAN TAWHID RISALAH AKHIRAH JANNAH RAHMA BARAKA NIKAH WALIMA ADHAN IQAMA IMAM KHATIB QARI HAFIZ ALIM MUFTI QADI UMRAH TAWAF SAI ARAFAT MINA MUZDALIFAH HIDAYAH NUR SIDQ ADIL AMIN Sadiq SALEH MUTTAQI MUHSIN MOMIN MUSLIM MUSLIMA UMMAH SUNNAH HADITH FIQH USUL IJMA QIYAS IJTIHAD FATWA HALAL HARAM MAKRUH MUBAH MUSTAHAB FARD WAJIB SUNNAHNAFIL SADAQA WAQF ZIKR ISTIGHFAR ASTAGHFIR TAWAKKUL TAWADU IKHLAQ ADAB AKHLAQ",
  nature:
    "TREE LEAF ROOT BARK BRANCH TWIG BUD BLOOM FLOWER PETAL SEED FRUIT MOSS FERN GRASS REED RUSH BUSH SHRUB HEDGE VINE IVY THORN SPINE NEEDLE CONE ACORN NUT BERRY FOREST WOODS GROVE GLEN GLADE MEADOW FIELD PRAIRIE PLAIN STEPPE TUNDRA TAIGA JUNGLE RAINFOREST SWAMP MARSH BOG FEN DELTA RIVER STREAM CREEK BROOK SPRING FALLS CASCADE RAPID POOL POND LAKE LOCH MERE TARN BAYOU LAGOON ISLAND ISLET REEF ROCK STONE PEBBLE BOULDER CLIFF CRAG PEAK RIDGE SLOPE VALLEY CANYON GORGE RAVINE GULCH PASS COL SADDLE SUMMIT CREST SPUR BUTTE MESA PLATEAU HIGHLAND LOWLAND BASIN DALE HOLLOW CAVE CAVERN GROTTO FISSURE FAULT CRATER VOLCANO LAVA MAGMA ASH CINDER SOIL CLAY LOAM SILT SAND DUST MUD SILTSTONE SANDSTONE GRANITE MARBLE SLATE QUARTZ MICA FELDSPAR CALCITE GYPSUM",
  verbs:
    "FIND SEEK LOOK SEE WATCH READ WRITE PLAY LEARN TEACH THINK KNOW FEEL HEAR SPEAK TALK TELL ASK CALL COME GO RUN WALK JUMP CLIMB SWIM FLY DRIVE RIDE SAIL ROW PADDLE THROW CATCH KICK HIT PUSH PULL LIFT CARRY HOLD KEEP GIVE TAKE SEND BRING OPEN CLOSE START STOP BEGIN END WIN LOSE DRAW TIE BUILD MAKE CREATE DRAW PAINT SING DANCE COOK BAKE MIX STIR CUT CHOP SLICE DICE PEEL BOIL FRY GRILL ROAST STEAM BAKE SERVE EAT DRINK SIP BITE CHEW TASTE SMELL TOUCH REST SLEEP WAKE RISE FALL GROW BLOOM FADE SHINE GLOW SPARK BURN MELT FREEZE THAW FLOW POUR SPILL FILL EMPTY LOAD SAVE LOAD STORE FETCH",
  adjectives:
    "FAST SLOW QUICK SWIFT RAPID BRISK LIVELY CALM QUIET LOUD SOFT HARD FIRM SOLID STURDY TOUGH WEAK FRAIL THIN THICK WIDE NARROW LONG SHORT TALL HIGH LOW DEEP SHALLOW BIG LARGE HUGE VAST TINY SMALL MINUTE GRAND NOBLE FINE FAIR GOOD BEST WORST BAD POOR RICH FULL EMPTY LIGHT DARK BRIGHT DIM DULL SHARP BLUNT SMOOTH ROUGH SILKY VELVET WARM COOL COLD ICY HOT MILD SPICY SWEET SOUR BITTER SALTY FRESH STALE NEW OLD ANCIENT YOUNG RIPE RAW COOKED BAKED FRIED BOILED GRILLED SMOKED CURED AGED RARE COMMON UNIQUE RARE ODD EVEN TRUE FALSE REAL FAKE OPEN SHUT CLEAR CLOUDY SUNNY RAINY WINDY SNOWY ICY FOGGY",
  numbers:
    "ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN ELEVEN TWELVE THIRTEEN FOURTEEN FIFTEEN SIXTEEN SEVENTEEN EIGHTEEN NINETEEN TWENTY THIRTY FORTY FIFTY SIXTY SEVENTY EIGHTY NINETY HUNDRED THOUSAND MILLION BILLION TRILLION ZERO NIL NAUGHT DOZEN SCORE PAIR TRIO QUAD GROSS HALF QUARTER THIRD FIFTH TENTH FIRST SECOND THIRD FOURTH FIFTH SIXTH SEVENTH EIGHTH NINTH TENTH LAST NEXT PREVIOUS SINGLE DOUBLE TRIPLE",
  shapes:
    "CIRCLE SQUARE TRIANGLE RECTANGLE OVAL ELLIPSE DIAMOND RHOMBUS HEXAGON OCTAGON PENTAGON HEPTAGON NONAGON DECAGON STAR HEART CROSS PLUS MINUS ARROW SPIRAL HELIX WAVE LINE DOT POINT ARC CHORD RADIUS DIAMETER TANGENT SECANT ANGLE ACUTE OBTUSE RIGHT CUBE SPHERE CONE CYLINDER PYRAMID PRISM TORUS RING DISK PLANE SOLID HOLLOW CURVE BEND TWIST FOLD CREASE EDGE VERTEX FACE SIDE CORNER CENTER MIDDLE AXIS",
  music:
    "SONG TUNE MELODY HARMONY RHYTHM BEAT TEMPO PITCH TONE NOTE CHORD SCALE KEY MAJOR MINOR MODE OCTAVE INTERVAL FIFTH FOURTH THIRD SECOND UNISON OCTAVE CLEF STAFF BAR REST SLUR TIE DOT SHARP FLAT NATURAL ACCIDENTAL FORTE PIANO ALLEGRO ADAGIO ANDANTE LARGO PRESTO VIVACE SONATA SYMPHONY CONCERTO OPERA ARIA CHORUS CHOIR ORCHESTRA BAND ENSEMBLE QUARTET TRIO DUET SOLO PIANO VIOLIN VIOLA CELLO BASS GUITAR HARP FLUTE OBOE CLARINET SAXOPHONE TRUMPET TROMBONE TUBA HORN DRUM CYMBAL SNARE TOM HIKE TIMPANI XYLOPHONE MARIMBA VIBRAPHONE ORGAN HARPSICHORD LUTE SITAR TABLA SITAR SAROD SANTOOR RABAB DHOL NAAT QAWALI GHAZAL",
  vehicles:
    "CAR BUS VAN TRUCK LORRY TAXI CAB TRAIN TRAM METRO SUBWAY RAIL ENGINE COACH WAGON CART CARRIAGE BIKE CYCLE SCOOTER MOPED MOTORCYCLE CHOPPER ATV JEEP SUV SEDAN COUPE HATCHBACK WAGON PICKUP TRAILER TANKER TANKERSHIP FERRY BOAT SHIP YACHT CANOE KAYAK RAFT BARGE TUG TANKER CRUISER DESTROYER CARRIER SUBMARINE JET PLANE GLIDER CHOPPER HELICOPTER DRONE ROCKET SHUTTLE BALLOON AIRSHIP BLIMP TRAM TROLLEY CABLECAR FUNICULAR SLED SLEIGH SNOWMOBILE HOVERCRAFT HYDROFOIL CATAMARAN TRIMARAN SCHOONER CLIPPER GALLEON JUNK SAMPAN DHOW FELUCCA",
  clothing:
    "SHIRT PANT TROUSER JEANS SHORTS SKIRT DRESS GOWN ROBE COAT JACKET BLAZER SWEATER HOODIE JUMPER CARDIGAN VEST WAISTCOAT TUNIC KAFTAN KURTA SHALWAR KAMEEZ SHERWANI WAISTCOAT DUPATTA CHADOR HIJAB SCARF SHAWL STOLE CAP HAT BERET BEANIE TURBAN TOPI HELMET CROWN TIARA BAND GLOVE MITTEN SOCK STOCKING TIGHTS HOSE SHOE BOOT SANDAL SLIPPER LOAFER SNEAKER HEEL PUMP FLAT BELT SASH TIE CRAVAT BOW CUFF COLLAR LAPEL POCKET BUTTON ZIPPER SNAP LACE RIBBON FRILL PLEAT HEM CUFF LINING LINING FABRIC COTTON SILK WOOL LINEN DENIM LEATHER SUEDE VELVET SATIN CHIFFON ORGANZA BROCADE",
  furniture:
    "CHAIR TABLE DESK SOFA COUCH BED COT CRIB CRADLE BENCH STOOL OTTOMAN SETTEE LOVESEAT RECLINER ROCKING WARDROBE CLOSET CABINET CUPBOARD DRESSER DRAWER SHELF BOOKCASE SIDEBOARD BUFFET HUTCH ARMOIRE CHEST TRUNK BOX CASE RACK STAND LAMP LIGHT MIRROR FRAME CLOCK VASE POT URN BOWL DISH PLATE CUP MUG GLASS JUG PITCHER TRAY BASKET BIN BUCKET PAIL MAT RUG CARPET RUNNER CUSHION PILLOW BLANKET QUILT DUVET SHEET CURTAIN DRAPE BLIND SCREEN PARTITION DIVIDER DOOR WINDOW SILL LEDGE RAIL POST PILLAR COLUMN ARCH BEAM JOIST PLANK BOARD PANEL TILE",
  school:
    "SCHOOL CLASS ROOM DESK CHALK BOARD BOOK PENCIL PEN INK PAGE PAPER NOTE COPY EXAM TEST QUIZ GRADE MARK SCORE PASS FAIL STUDY LEARN TEACH TUTOR MENTOR PUPIL STUDENT TEACHER PRINCIPAL DEAN RECTOR LIBRARIAN LAB SCIENCE MATH HISTORY GEOGRAPHY CIVICS ART MUSIC SPORT DRAMA DEBATE CLUB TEAM HOUSE BELL BREAK LUNCH RECESS ASSEMBLY PRAYER LESSON CHAPTER TOPIC HOMEWORK PROJECT ESSAY REPORT THESIS DEGREE DIPLOMA CERTIFICATE SCHOLAR AWARD PRIZE MEDAL TROPHY BADGE HONOR MERIT RANK ROLL ATTEND ABSENT LATE EARLY UNIFORM BAG SATCHEL BACKPACK LOCKER HALL CORRIDOR STAIR CAMPUS QUAD FIELD GYM LIBRARY LAB",
  hospital:
    "HOSPITAL CLINIC WARD ROOM BED NURSE DOCTOR SURGEON DENTIST VET PHARMACY LAB XRAY SCAN MRI CT ULTRASOUND PILL TABLET CAPSULE SYRUP DROP INJECTION VACCINE SERUM SALINE STITCH SUTURE BANDAGE GAUZE CAST SPLINT CRUTCH WHEELCHAIR STRETCHER AMBULANCE TRIAGE EMERGENCY ICU NICU OT THEATRE ANESTHESIA SCALPEL FORCEPS CLAMP PROBE SCOPE MASK GLOVE GOWN CAP BOOTIE ANTISEPTIC ALCOHOL IODINE MERCURY THERMOMETER PULSE OXIMETER MONITOR DEFIBRILLATOR VENTILATOR DIALYSIS TRANSFUSION DONOR BLOOD PLASMA PLATELET CELL GERM VIRUS BACTERIA FUNGUS INFECTION FEVER COUGH COLD FLU ASTHMA ALLERGY RASH BURN WOUND FRACTURE SPRAIN STRAIN BRUISE SWELL PAIN ACHE MIGRAINE NAUSEA VOMIT DIARRHEA CONSTIPATION ANEMIA DIABETES",
  kitchen:
    "KITCHEN STOVE OVEN GRILL TOASTER KETTLE POT PAN WOK KADHAI TAWA GRIDDLE SKILLET SAUCEPAN CASSEROLE DISH BOWL PLATE SAUCER CUP MUG GLASS JUG PITCHER BOTTLE JAR TIN CAN BOX BAG FOIL WRAP FILM LID COVER SPOON FORK KNIFE LADLE SPATULA WHISK TONGS PEELER GRATER SLICER CHOPPER BOARD MORTAR PESTLE MILL GRINDER MIXER BLENDER PROCESSOR JUICER SQUEEZER SIEVE STRAINER COLANDER FUNNEL SCALE TIMER CLOCK RECIPE MENU SPICE RACK SALT PEPPER CHILI TURMERIC CUMIN CORIANDER CARDAMOM CLOVE CINNAMON NUTMEG MACE FENNEL MUSTARD SESAME POPPY SAFFRON PAPRIKA OREGANO BASIL THYME ROSEMARY SAGE MINT PARSLEY DILL",
  tools:
    "HAMMER NAIL SCREW BOLT NUT WASHER RIVET PIN CLIP CLAMP VISE PLIERS WRENCH SPANNER SOCKET RATCHET DRIVER DRILL BIT SAW BLADE CHISEL FILE RASP PLANE LATHE MILL GRINDER SANDER POLISHER BRUSH ROLLER TROWEL FLOAT LEVEL SQUARE TAPE RULE GAUGE CALIPER MICROMETER COMPASS PROTRACTOR DIVIDER PUNCH AWL AWL REAMER TAP DIE THREAD PIPE FITTING VALVE TAP HOSE PUMP JACK LIFT HOIST CRANE WINCH PULLEY GEAR LEVER WEDGE INCLINE SCREW SPRING HINGE LATCH LOCK KEY HANDLE KNOB SWITCH BUTTON LEVER DIAL METER GAUGE SENSOR PROBE TESTER METER TORCH LAMP LIGHT BATTERY CELL WIRE CABLE FUSE PLUG SOCKET OUTLET",
  flowers:
    "ROSE LILY TULIP DAISY IRIS ORCHID JASMINE LOTUS MARIGOLD SUNFLOWER LAVENDER VIOLET POPPY DAHLIA PEONY CARNATION CHRYSANTHEMUM ASTER ZINNIA PANSY PETUNIA BEGONIA GERANIUM FUCHSIA HIBISCUS MAGNOLIA CAMELLIA AZALEA RHODODENDRON GARDENIA FREESIA HYACINTH DAFFODIL NARCISSUS CROCUS SNOWDROP BLUEBELL FOXGLOVE SNAPDRAGON LARKSPUR DELPHINIUM LUPINE WISTERIA CLEMATIS HONEYSUCKLE JASMINE GARDENIA LILAC MOCKORANGE FORSYTHIA WEIGELA SPIREA HYDRANGEA ANEMONE RANUNCULUS HELLEBORE PRIMROSE CYCLAMEN AFRICANVIOLET IMPATIENS COLEUS SALVIA VERBENA LANTANA BOUGAINVILLEA PLUMERIA FRANGIPANI OLEANDER BOUGAINVILLEA IXORA CROSSANDRA",
  trees:
    "OAK PINE FIR SPRUCE CEDAR CYPRESS YEW LARCH HEMLOCK REDWOOD SEQUOIA MAPLE BIRCH BEECH ASH ELM LINDEN POPLAR WILLOW ASPEN ALDER HAZEL WALNUT HICKORY PECAN CHESTNUT BEECHCHINQUAPIN OAKLIVE SYCAMORE PLANE MULBERRY FIG OLIVE DATE PALM COCONUT BANANA BAMBOO TEAK SAL DEODAR CHINAR CHENAR NEEM PEEPAL BANYAN MANGO GUAVA JAMUN AMALTAS GULMOHAR JACARANDA LABURNUM ACACIA MIMOSA ALBIZIA CASUARINA EUCALYPTUS BOTTLEBRUSH CALLISTEMON MELALEUCA LEPTOSPERMUM KUNZEA BANKSIA GREVILLEA HAKEA PROTEA WARATAH WATTLE GOLDENWATTLE SILVERWATTLE BLACKWOOD IRONBARK BLOODWOOD STRINGYBARK",
  insects:
    "ANT BEE WASP HORNET FLY GNAT MIDGE MOSQUITO MOTH BUTTERFLY CATERPILLAR LARVA PUPA CHRYSALIS COCOON BEETLE WEEVIL LADYBUG FIREFLY GLOWWORM CRICKET GRASSHOPPER LOCUST KATYDID CICADA APHID TERMITE MANTIS DRAGONFLY DAMSELFLY MAYFLY STONEFLY CADDISFLY LACEWING SCORPIONFLY FLEAHOPPER LEAFHOPPER PLANTHOPPER TREEHOPPER FROGHOPPER SPITTLEBUG SHIELDBUG STINKBUG BEDBUG APHIDLION LACEWING ANTLION DOODLEBUG EARWIG SILVERFISH BRISTLETAIL SPRINGTAIL THRIPS WHITEFLY MEALYBUG SCALE PSYLLA LEAFMINER BORER WEEVIL CURCULIO SNOUTBEETLE",
  fish:
    "TUNA SALMON COD TROUT BASS PIKE PERCH CARP KOI GOLDFISH GUPPY TETRA DISCUS ANGEL BETTA Gourami BARB DANIO RASBORA MOLLY PLATY SWORDTAIL CORY CATFISH PLECO LOACH EEL MORAY CONGER LAMPREY HAGFISH SHARK RAY SKATE SAWFISH GUITARFISH CHIMAERA RATFISH STURGEON PADDLEFISH BOWFIN GAR PIRARUCU ARAPAIMA AROWANA OSTEOGLOSSUM BUTTERFLYFISH BANNERFISH TANG WRASSE PARROTFISH CLOWNFISH DAMSEL GOBY BLENNY WRASSE GROUPER SNAPPER JACK TREVALLY POMPANO PERMIT COBIA MAHI WAHOO BARRACUDA MACKEREL BONITO SKIPJACK ALBACORE YELLOWFIN BLUEFIN BIGEYE",
  urdu:
    "KITAB QALAM DAWAT KAGHAZ DIL JAN DUA PYAR MOHABBAT DOST YAAR WATAN GULAB CHAND SURAJ SITARA RAAT DIN SUBAH SHAM HAWA PANI AAG MITTI PATTA PHOOL PERH PAHARR DARYA SAMANDAR JUNGLE BAGH GULSHAN BAHAR KHAZAN BARISH BARF OOND ANDHERA UJALA ROSHNI SAYA KHUSHI GHAM HANSNA RONA GEET NAGHMA SAZ DAF TABLA SITAR RABAB DILRUBA QAWALI GHAZAL NAAT HAMN SHEIR MISRA QASIDA MASNAVI DASTAN QISSA KAHANI AFSANA NOVEL DRAMA FILM TAMASHA MELA EID ROZA NAMAZ MASJID MIMBAR MEHRAB TASBIH TASBEH JANAMAZ TOPI AMAMA SHALWAR KAMEEZ DUPATTA CHADDAR SHERWANI WAISTCOAT JUTA KHUSA CHAPPAL CHAI DOODH ROTI SALAN BIRYANI KEBAB TIKKA NIHARI HALEEM Lassi KULFI KHEER HALWA JALEBI SAMOSA PAKORA CHUTNEY ACHAR DHI AAM SEB KELA ANAR ANGUR NASPATI AALU PYAZ LEHSAN ADRAK HALDI MIRCH ZEERA DHANIA",
  roman:
    "PYAAR MOHABBAT DOSTI YAARI WATAN QOUM MILLAT IZZAT GHURAT HIMMAT HIMMAT JUNOON JAZBA ARMAN KHWAB UMANG UMMEED SABAR SHUKR TAQWA IMAN YAQEEN TAWAKKUL TAWBA DUA MUNAJAT ZIKR FIKR FIKR SOCH SAMAJH AQL ILM HIKMAT ADAB AKHLAQ TEHZEEB SAQAFAT RIWAYAT RASM RASM RIVAIT ADAAT LIBAAS POSHAAK LIBAAS KAPRA KAPRE KAPRA JORA JOORA JORA KAPRA KAPRE KAPRA",
};

const URDU_SCRIPT =
  "کتاب قلم کاغذ دل جان دعا پیار محبت دوست یار وطن گلاب چاند سورج ستارہ رات دن صبح شام ہوا پانی آگ مٹی پتہ پھول پہاڑ دریا سمندر جنگل باغ بہار خزاں بارش برف اندھیرا اجالا روشنی سایہ خوشی غم ہنسنا رونا گیت نغمہ ساز دف طبلہ ستار رباب عید روزہ نماز مسجد محراب تسبیح ٹوپی شلوار قمیض دوپٹہ چادر شیروانی جوتا چپل چائے دودھ روٹی سالن بریانی کباب تکہ نہاری حلیم لسی قلفی کھیر حلوہ جلیبی سموسہ پکوڑا چٹنی اچار آم سیب کیلا انار انگور ناشپاتی آلو پیاز لہسن ادرک ہلدی مرچ زیرہ دھنیا";

function tokenize(raw: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const part of raw.split(/[\s,]+/)) {
    const w = part.trim().toUpperCase();
    if (w.length < 3 || w.length > 14) continue;
    if (!/^[A-Z]+$/.test(w)) continue;
    if (seen.has(w)) continue;
    seen.add(w);
    out.push(w);
  }
  return out;
}

export const CATEGORIES: Record<string, string[]> = Object.fromEntries(
  Object.entries(RAW).map(([k, v]) => [k, tokenize(v)]),
);

export const URDU_WORDS = URDU_SCRIPT.split(/\s+/).filter((w) => w.length >= 2 && w.length <= 10);

export const CATEGORY_IDS = Object.keys(CATEGORIES);

const ALL_SET = new Set<string>();
for (const list of Object.values(CATEGORIES)) {
  for (const w of list) ALL_SET.add(w);
}
for (const w of EXTENDED_WORDS) ALL_SET.add(w);
export const ALL_WORDS = [...ALL_SET];

export function isWord(w: string) {
  return ALL_SET.has(w.toUpperCase());
}

export function wordsInRange(minLen: number, maxLen: number, category?: string): string[] {
  const pool = category && CATEGORIES[category] ? CATEGORIES[category]! : ALL_WORDS;
  return pool.filter((w) => w.length >= minLen && w.length <= maxLen);
}

export function categoryOf(word: string): string | undefined {
  const u = word.toUpperCase();
  for (const [id, list] of Object.entries(CATEGORIES)) {
    if (list.includes(u)) return id;
  }
  return undefined;
}

export const WORD_COUNT = ALL_WORDS.length;
