import { useMemo, useState } from "react";
import { Download, FileCheck2, ShieldCheck } from "lucide-react";
import { Screen } from "@/components/screens/chrome";
import { buildReleasePackage, downloadReleasePackage, listReleaseCandidates, type CreatorReleasePackage } from "@/lib/v40_releasePackage";
import { useGame } from "@/lib/store";

export function ReleasePackageScreen(){
 const go=useGame.getState().go; const candidates=useMemo(()=>listReleaseCandidates(),[]); const [selected,setSelected]=useState(candidates[0]?.draft.id||""); const [pkg,setPkg]=useState<CreatorReleasePackage|null>(null); const [busy,setBusy]=useState(false);
 const build=async()=>{setBusy(true);try{setPkg(await buildReleasePackage(selected));}finally{setBusy(false)}}; const item=candidates.find(x=>x.draft.id===selected);
 return <Screen title="Release Package"><div className="grid gap-4"><section className="panel rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-primary">V40 creator delivery</p><h2 className="font-display mt-1 text-2xl text-fg">Package a verified puzzle</h2><p className="mt-2 text-sm text-muted">Creates a portable JSON release artifact containing the draft, publish-readiness snapshot and an integrity digest. It never publishes automatically.</p></section>
 <section className="panel rounded-2xl p-4"><select value={selected} onChange={e=>{setSelected(e.target.value);setPkg(null)}} className="w-full rounded-xl border border-border bg-surface px-3 py-3 text-fg"><option value="">Choose a Creator draft</option>{candidates.map(x=><option key={x.draft.id} value={x.draft.id}>{x.draft.title} · {x.readiness?.score??0}/100</option>)}</select>{item&&<p className="mt-3 text-sm text-muted">Readiness: {item.readiness?.ready?"Ready":"Needs another pass"} · QA {item.readiness?.audit.score}/100</p>}</section>
 <button disabled={!selected||busy} onClick={build} className="flex items-center justify-center gap-2 rounded-xl border border-border px-4 py-3 text-sm font-semibold text-fg disabled:opacity-50"><FileCheck2 className="size-4"/>{busy?"Building package…":"Build verified release package"}</button>
 {pkg&&<section className="panel rounded-2xl p-5 grid gap-4"><div className="flex items-center gap-2 text-fg"><ShieldCheck className="size-5 text-primary"/><b>Release artifact ready</b></div><div className="grid gap-2 text-sm text-muted"><p><b className="text-fg">Puzzle:</b> {pkg.draft.title}</p><p><b className="text-fg">Readiness:</b> {pkg.readiness.score}/100 · {pkg.readiness.ready?"ready":"blocked"}</p><p><b className="text-fg">Integrity:</b> {pkg.integrity.algorithm}</p><p className="break-all"><b className="text-fg">Digest:</b> {pkg.integrity.digest}</p></div><button onClick={()=>downloadReleasePackage(pkg)} className="flex items-center justify-center gap-2 rounded-xl border border-border px-4 py-3 text-sm font-semibold text-fg"><Download className="size-4"/>Export JSON package</button></section>}
 <div className="flex flex-wrap gap-4"><button onClick={()=>go("publishReadiness")} className="text-sm text-primary">← Publish Readiness</button><button onClick={()=>go("creator")} className="text-sm text-primary">Creator Studio →</button><button onClick={()=>go("more")} className="text-sm text-muted">More</button></div></div></Screen>;
}
