-- Player/admin analytics: stable player numbers + activity/play-time tracking.
create sequence if not exists player_number_seq start 100001;\n\nalter table "user" add column if not exists "username" text;

create table if not exists player_profile (
  user_id text primary key references "user" ("id") on delete cascade,
  player_number bigint not null unique default nextval('player_number_seq'),
  username text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists player_activity (
  id bigint generated by default as identity primary key,
  user_id text not null references "user" ("id") on delete cascade,
  event_type text not null,
  screen text,
  occurred_at timestamptz not null default current_timestamp,
  duration_seconds integer not null default 0
);

create index if not exists player_activity_user_time_idx
  on player_activity (user_id, occurred_at desc);

create table if not exists player_presence (
  user_id text primary key references "user" ("id") on delete cascade,
  first_seen_at timestamptz not null default current_timestamp,
  last_seen_at timestamptz not null default current_timestamp,
  total_play_seconds bigint not null default 0,
  current_screen text
);

create index if not exists player_presence_last_seen_idx
  on player_presence (last_seen_at desc);
