-- Online multiplayer matchmaking, matches and chat.
create table if not exists multiplayer_match (
  id text primary key,
  player_a text not null references "user" ("id") on delete cascade,
  player_b text references "user" ("id") on delete set null,
  status text not null default 'waiting',
  puzzle_seed bigint not null,
  score_a integer not null default 0,
  score_b integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists multiplayer_waiting_idx
  on multiplayer_match (status, updated_at desc);

create index if not exists multiplayer_player_idx
  on multiplayer_match (player_a, player_b, updated_at desc);

create table if not exists multiplayer_message (
  id bigint generated by default as identity primary key,
  match_id text not null references multiplayer_match (id) on delete cascade,
  user_id text not null references "user" ("id") on delete cascade,
  message text not null,
  created_at timestamptz not null default current_timestamp
);

create index if not exists multiplayer_message_match_idx
  on multiplayer_message (match_id, created_at desc);
