import { createServerFn } from "@tanstack/react-start";
import { getPrisma } from "@/lib/db";
import { authMiddleware } from "@/lib/auth/middleware";
import { requirePermission } from "@/lib/security/authorization.server";
const clean=(v:unknown,n:number)=>String(v??"").trim().slice(0,n);
export const submitCreatorForReview=createServerFn({method:"POST"}).middleware([authMiddleware]).validator((d:{id:string})=>({id:clean(d.id,80)})).handler(async({context,data})=>{const r=await getPrisma().creatorPuzzle.updateMany({where:{id:data.id,userId:context.userId},data:{status:"pending_review"}});return{ok:r.count===1 as const}});
export const listCreatorCommunity=createServerFn({method:"GET"}).middleware([authMiddleware]).handler(async()=>{const rows=await getPrisma().creatorPuzzle.findMany({where:{status:"approved"},include:{reviews:{select:{rating:true}}},orderBy:{updatedAt:"desc"},take:50});return rows.map(p=>({id:p.id,title:p.title,category:p.category,status:p.status,version:p.version,rating:p.reviews.length?p.reviews.reduce((s,r)=>s+r.rating,0)/p.reviews.length:0,review_count:p.reviews.length}))});
export const reviewCreatorPuzzle=createServerFn({method:"POST"}).middleware([authMiddleware]).validator((d:{puzzleId:string;rating:number;body?:string})=>({puzzleId:clean(d.puzzleId,80),rating:Math.max(1,Math.min(5,Math.floor(Number(d.rating)))),body:clean(d.body,500)})).handler(async({context,data})=>{const db=getPrisma();if(await db.creatorPuzzle.findFirst({where:{id:data.puzzleId,userId:context.userId},select:{id:true}}))return{ok:false as const,error:"You cannot review your own puzzle"};await db.creatorReview.upsert({where:{puzzleId_userId:{puzzleId:data.puzzleId,userId:context.userId}},create:{puzzleId:data.puzzleId,userId:context.userId,rating:data.rating,body:data.body},update:{rating:data.rating,body:data.body}});return{ok:true as const}});
export const moderateCreatorPuzzle=createServerFn({method:"POST"}).middleware([authMiddleware]).validator((d:{id:string;status:"approved"|"rejected"|"pending_review"})=>({id:clean(d.id,80),status:d.status})).handler(async({context,data})=>{try{await requirePermission(context.userId,"creator.moderate")}catch{return{ok:false as const,error:"Admin access required"}}const r=await getPrisma().creatorPuzzle.updateMany({where:{id:data.id},data:{status:data.status}});return{ok:r.count===1 as const}});
