/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMultiplayerActionRouteImport } from './routes/api/multiplayer/action'
import { Route as ApiMultiplayerMatchRouteImport } from './routes/api/multiplayer/match'
import { Route as ApiMultiplayerStateRouteImport } from './routes/api/multiplayer/state'
import { Route as ApiPaymentsBaseRouteImport } from './routes/api/payments/base'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMultiplayerActionRoute = ApiMultiplayerActionRouteImport.update({
  id: '/api/multiplayer/action',
  path: '/api/multiplayer/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMultiplayerMatchRoute = ApiMultiplayerMatchRouteImport.update({
  id: '/api/multiplayer/match',
  path: '/api/multiplayer/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMultiplayerStateRoute = ApiMultiplayerStateRouteImport.update({
  id: '/api/multiplayer/state',
  path: '/api/multiplayer/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsBaseRoute = ApiPaymentsBaseRouteImport.update({
  id: '/api/payments/base',
  path: '/api/payments/base',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/multiplayer/action': typeof ApiMultiplayerActionRoute
  '/api/multiplayer/match': typeof ApiMultiplayerMatchRoute
  '/api/multiplayer/state': typeof ApiMultiplayerStateRoute
  '/api/payments/base': typeof ApiPaymentsBaseRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/multiplayer/action': typeof ApiMultiplayerActionRoute
  '/api/multiplayer/match': typeof ApiMultiplayerMatchRoute
  '/api/multiplayer/state': typeof ApiMultiplayerStateRoute
  '/api/payments/base': typeof ApiPaymentsBaseRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/multiplayer/action': typeof ApiMultiplayerActionRoute
  '/api/multiplayer/match': typeof ApiMultiplayerMatchRoute
  '/api/multiplayer/state': typeof ApiMultiplayerStateRoute
  '/api/payments/base': typeof ApiPaymentsBaseRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/shop'
    | '/api/auth/$'
    | '/api/multiplayer/action'
    | '/api/multiplayer/match'
    | '/api/multiplayer/state'
    | '/api/payments/base'
    | '/api/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/shop'
    | '/api/auth/$'
    | '/api/multiplayer/action'
    | '/api/multiplayer/match'
    | '/api/multiplayer/state'
    | '/api/payments/base'
    | '/api/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/shop'
    | '/api/auth/$'
    | '/api/multiplayer/action'
    | '/api/multiplayer/match'
    | '/api/multiplayer/state'
    | '/api/payments/base'
    | '/api/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMultiplayerActionRoute: typeof ApiMultiplayerActionRoute
  ApiMultiplayerMatchRoute: typeof ApiMultiplayerMatchRoute
  ApiMultiplayerStateRoute: typeof ApiMultiplayerStateRoute
  ApiPaymentsBaseRoute: typeof ApiPaymentsBaseRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multiplayer/action': {
      id: '/api/multiplayer/action'
      path: '/api/multiplayer/action'
      fullPath: '/api/multiplayer/action'
      preLoaderRoute: typeof ApiMultiplayerActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multiplayer/match': {
      id: '/api/multiplayer/match'
      path: '/api/multiplayer/match'
      fullPath: '/api/multiplayer/match'
      preLoaderRoute: typeof ApiMultiplayerMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multiplayer/state': {
      id: '/api/multiplayer/state'
      path: '/api/multiplayer/state'
      fullPath: '/api/multiplayer/state'
      preLoaderRoute: typeof ApiMultiplayerStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/base': {
      id: '/api/payments/base'
      path: '/api/payments/base'
      fullPath: '/api/payments/base'
      preLoaderRoute: typeof ApiPaymentsBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMultiplayerActionRoute: ApiMultiplayerActionRoute,
  ApiMultiplayerMatchRoute: ApiMultiplayerMatchRoute,
  ApiMultiplayerStateRoute: ApiMultiplayerStateRoute,
  ApiPaymentsBaseRoute: ApiPaymentsBaseRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
