import type { LangCode } from "./types.ts";

/** Curated offline starter vocabulary for every supported language.
 * These are gameplay tokens (single words/lexemes), intentionally kept
 * conservative so they render cleanly in a word grid without punctuation.
 * The large English lexicon remains the fallback for languages not yet
 * carrying a full 5,000-word corpus.
 */
export const NATIVE_WORDS: Record<LangCode, string[]> = {
  en: ["WORD","SEARCH","GAME","JOURNEY","PUZZLE","BOOK","PAPER","PEN","HOME","FAMILY","FRIEND","WATER","FIRE","EARTH","WIND","LIGHT","NIGHT","MORNING","SUN","MOON","STAR","FLOWER","TREE","RIVER","MOUNTAIN","FOREST","OCEAN","ISLAND","GARDEN","APPLE","MANGO","ORANGE","BANANA","LEMON","PEACH","CHERRY","GRAPE","CARROT","POTATO","TOMATO","ONION","GARLIC","BREAD","RICE","MILK","TEA","COFFEE","HORSE","TIGER","LION","EAGLE","DOLPHIN","WHALE","RABBIT","FOX","BEAR","WOLF","BIRD","FISH","MUSIC","SONG","STORY","DREAM","HOPE","SMILE","PEACE","BRAVE","HAPPY","QUIET","TRAVEL","WORLD","CITY","SCHOOL","LEARN","CREATE","PLAY","WIN","LEVEL","COIN","MAGIC","SECRET","TREASURE","CASTLE","CLOUD","RAIN","SNOW","SPRING","SUMMER","AUTUMN","WINTER"],
  ur: ["لفظ","تلاش","کھیل","سفر","پہیلی","کتاب","قلم","کاغذ","گھر","خاندان","دوست","پانی","آگ","مٹی","ہوا","روشنی","رات","صبح","سورج","چاند","ستارہ","پھول","درخت","دریا","پہاڑ","جنگل","سمندر","جزیرہ","باغ","سیب","آم","مالٹا","کیلا","لیموں","آڑو","انگور","گاجر","آلو","ٹماٹر","پیاز","لہسن","روٹی","چاول","دودھ","چائے","کافی","گھوڑا","شیر","باز","عقاب","مچھلی","وہیل","خرگوش","لومڑی","ریچھ","بھیڑیا","پرندہ","موسیقی","گانا","کہانی","خواب","امید","مسکراہٹ","امن","بہادر","خوش","خاموش","دنیا","شہر","مدرسہ","سیکھنا","تخلیق","جیت","سکہ","جادو","راز","خزانہ","قلعہ","بادل","بارش","برف","بہار","گرمی","خزاں","سردی"],
  "ur-Latn": ["LAFZ","TALAASH","KHEL","SAFAR","PAHELI","KITAB","QALAM","KAGHAZ","GHAR","KHANDAN","DOST","PANI","AAG","MITTI","HAWA","ROSHNI","RAAT","SUBAH","SURAJ","CHAAND","SITARA","PHOOL","DARAKHT","DARYA","PAHAR","JUNGLE","SAMANDAR","JAZEERA","BAAG","SEB","AAM","MALTA","KELA","LEMON","AARO","ANGUR","GAJAR","AALU","TAMATAR","PIYAZ","LEHSAN","ROTI","CHAWAL","DOODH","CHAI","KAHWA","GHORA","SHER","BAAZ","AQAB","MACHHLI","DOLPHIN","KHARGOSH","LOMARI","REESH","BHERIYA","PARINDA","MOUSIQI","GEET","KAHANI","KHWAAB","UMEED","MUSKURAHAT","AMAN","BAHADUR","KHUSH","KHAMOSH","DUNIYA","SHEHAR","MADARSA","SEEKHNA","TAKHLEEQ","JEET","SIKKA","JADOO","RAAZ","KHAZANA","QILA","BADAL","BARISH","BARAF","BAHAAR","GARMI","KHAZAN","SARDI"],
  hi: ["शब्द","खोज","खेल","सफर","पहेली","किताब","कलम","कागज","घर","परिवार","दोस्त","पानी","आग","मिट्टी","हवा","रोशनी","रात","सुबह","सूरज","चाँद","तारा","फूल","पेड़","नदी","पहाड़","जंगल","समुद्र","द्वीप","बगीचा","सेब","आम","संतरा","केला","नींबू","आड़ू","अंगूर","गाजर","आलू","टमाटर","प्याज","लहसुन","रोटी","चावल","दूध","चाय","कॉफी","घोड़ा","शेर","बाज़","गरुड़","मछली","व्हेल","खरगोश","लोमड़ी","भालू","भेड़िया","पक्षी","संगीत","गीत","कहानी","सपना","आशा","मुस्कान","शांति","बहादुर","खुश","दुनिया","शहर","विद्यालय","सीखना","बनाना","जीत","सिक्का","जादू","रहस्य","खजाना","किला","बादल","बारिश","बर्फ","वसंत","गर्मी","पतझड़","सर्दी"],
  ar: ["كلمة","بحث","لعبة","رحلة","لغز","كتاب","قلم","ورق","بيت","عائلة","صديق","ماء","نار","تراب","هواء","نور","ليل","صباح","شمس","قمر","نجم","زهرة","شجرة","نهر","جبل","غابة","بحر","جزيرة","حديقة","تفاح","مانجو","برتقال","موز","ليمون","خوخ","عنب","جزر","بطاطس","طماطم","بصل","ثوم","خبز","أرز","حليب","شاي","قهوة","حصان","نمر","أسد","نسر","سمك","حوت","أرنب","ثعلب","دب","ذئب","طائر","موسيقى","أغنية","قصة","حلم","أمل","ابتسامة","سلام","شجاع","سعيد","عالم","مدينة","مدرسة","تعلم","إبداع","فوز","عملة","سحر","سر","كنز","قلعة","سحاب","مطر","ثلج","ربيع","صيف","خريف","شتاء"],
  bn: ["শব্দ","খোঁজ","খেলা","যাত্রা","ধাঁধা","বই","কলম","কাগজ","বাড়ি","পরিবার","বন্ধু","পানি","আগুন","মাটি","বায়ু","আলো","রাত","সকাল","সূর্য","চাঁদ","তারা","ফুল","গাছ","নদী","পাহাড়","বন","সমুদ্র","দ্বীপ","বাগান","আপেল","আম","কমলা","কলা","লেবু","আঙুর","গাজর","আলু","টমেটো","পেঁয়াজ","রসুন","রুটি","চাল","দুধ","চা","কফি","ঘোড়া","বাঘ","সিংহ","ঈগল","মাছ","তিমি","খরগোশ","শিয়াল","ভালুক","নেকড়ে","পাখি","সঙ্গীত","গান","গল্প","স্বপ্ন","আশা","হাসি","শান্তি","সাহসী","সুখী","বিশ্ব","শহর","বিদ্যালয়","শেখা","সৃষ্টি","জয়","মুদ্রা","জাদু","রহস্য","ধন","দুর্গ","মেঘ","বৃষ্টি","বরফ","বসন্ত","গ্রীষ্ম","শরৎ","শীত"],
  pa: ["ਸ਼ਬਦ","ਖੋਜ","ਖੇਡ","ਸਫ਼ਰ","ਬੁਝਾਰਤ","ਕਿਤਾਬ","ਕਲਮ","ਕਾਗਜ਼","ਘਰ","ਪਰਿਵਾਰ","ਦੋਸਤ","ਪਾਣੀ","ਅੱਗ","ਮਿੱਟੀ","ਹਵਾ","ਰੌਸ਼ਨੀ","ਰਾਤ","ਸਵੇਰ","ਸੂਰਜ","ਚੰਦ","ਤਾਰਾ","ਫੁੱਲ","ਰੁੱਖ","ਨਦੀ","ਪਹਾੜ","ਜੰਗਲ","ਸਮੁੰਦਰ","ਟਾਪੂ","ਬਾਗ","ਸੇਬ","ਅੰਬ","ਸੰਤਰਾ","ਕੇਲਾ","ਨਿੰਬੂ","ਅੰਗੂਰ","ਗਾਜਰ","ਆਲੂ","ਟਮਾਟਰ","ਪਿਆਜ਼","ਲਸਣ","ਰੋਟੀ","ਚੌਲ","ਦੁੱਧ","ਚਾਹ","ਕੌਫੀ","ਘੋੜਾ","ਬਾਘ","ਸ਼ੇਰ","ਬਾਜ਼","ਮੱਛੀ","ਵ੍ਹੇਲ","ਖਰਗੋਸ਼","ਲੂੰਬੜੀ","ਭਾਲੂ","ਬਘਿਆੜ","ਪੰਛੀ","ਸੰਗੀਤ","ਗੀਤ","ਕਹਾਣੀ","ਸੁਪਨਾ","ਉਮੀਦ","ਮੁਸਕਾਨ","ਅਮਨ","ਬਹਾਦਰ","ਖੁਸ਼","ਦੁਨੀਆ","ਸ਼ਹਿਰ","ਸਕੂਲ","ਸਿੱਖਣਾ","ਬਣਾਉਣਾ","ਜਿੱਤ","ਸਿੱਕਾ","ਜਾਦੂ","ਰਾਜ਼","ਖਜ਼ਾਨਾ","ਕਿਲ੍ਹਾ","ਬੱਦਲ","ਮੀਂਹ","ਬਰਫ਼","ਬਸੰਤ","ਗਰਮੀ","ਪਤਝੜ","ਸਰਦੀ"],
  sd: ["لفظ","ڳولا","راند","سفر","ڳجهارت","ڪتاب","قلم","ڪاغذ","گهر","ڪٽنب","دوست","پاڻي","باهه","مٽي","هوا","روشني","رات","صبح","سج","چنڊ","تارو","گل","وڻ","درياهه","جبل","جهنگ","سمنڊ","ٻيٽ","باغ","انب","صوف","نارنگي","ڪيلا","ليمو","انگور","گاجر","آلو","ٽماٽو","پياز","ٿوم","ماني","چانور","کير","چانهه","ڪافي","گهوڙو","شينهن","باز","عقاب","مڇي","وهيل","سهو","لومڙ","رڇ","بگهڙ","پکي","موسيقي","گيت","ڪهاڻي","خواب","اميد","مرڪ","امن","بهادر","خوش","دنيا","شهر","اسڪول","سکڻ","تخليق","فتح","سڪو","جادو","راز","خزانو","قلعو","بادل","مينهن","برف","بهار","اونهارو","سرءُ","سيارو"],
  ps: ["کلمه","لټون","لوبه","سفر","معما","کتاب","قلم","کاغذ","کور","کورنۍ","ملګری","اوبه","اور","خاوره","باد","رڼا","شپه","سهار","لمر","سپوږمۍ","ستوری","ګل","ونه","سیند","غر","ځنګل","سمندر","ټاپو","باغ","مڼه","ام","مالټه","کیله","لیمو","انګور","ګازرې","کچالو","رومیان","پیاز","هوږه","ډوډۍ","وریجې","شیدې","چای","قهوه","آس","پړانګ","زمری","باز","عقاب","کب","ویل","سوی","ګیدړ","خرس","لېوه","مرغه","موسیقي","سندرې","کیسه","خوب","هیله","موسکا","سوله","زړور","خوښ","نړۍ","ښار","ښوونځی","زده","جوړول","بریا","سکه","جادو","راز","خزانه","کلا","ورېځ","باران","واوره","پسرلی","اوړی","منی","ژمی"],
  tr: ["KELİME","ARAMA","OYUN","YOLCULUK","BULMACA","KITAP","KALEM","KAĞIT","EV","AİLE","DOST","SU","ATEŞ","TOPRAK","RÜZGAR","IŞIK","GECE","SABAH","GÜNEŞ","AY","YILDIZ","ÇİÇEK","AĞAÇ","NEHİR","DAĞ","ORMAN","DENİZ","ADA","BAHÇE","ELMA","MANGO","PORTAKAL","MUZ","LİMON","ŞEFTALİ","ÜZÜM","HAVUÇ","PATATES","DOMATES","SOĞAN","SARIMSAK","EKMEK","PİRİNÇ","SÜT","ÇAY","KAHVE","AT","KAPLAN","ASLAN","KARTAL","BALIK","BALİNA","TAVŞAN","TİLKİ","AYI","KURT","KUŞ","MÜZİK","ŞARKI","HİKAYE","RÜYA","UMUT","GÜLÜMSEME","BARIŞ","CESUR","MUTLU","DÜNYA","ŞEHİR","OKUL","ÖĞRENMEK","YARATMAK","KAZANMAK","MADENİ","BÜYÜ","SIR","HAZİNE","KALE","BULUT","YAĞMUR","KAR","BAHAR","YAZ","SONBAHAR","KIŞ"],
  es: ["PALABRA","BUSCAR","JUEGO","VIAJE","ROMPECABEZAS","LIBRO","PLUMA","PAPEL","CASA","FAMILIA","AMIGO","AGUA","FUEGO","TIERRA","VIENTO","LUZ","NOCHE","MAÑANA","SOL","LUNA","ESTRELLA","FLOR","ÁRBOL","RÍO","MONTAÑA","BOSQUE","MAR","ISLA","JARDÍN","MANZANA","MANGO","NARANJA","PLÁTANO","LIMÓN","MELOCOTÓN","UVA","ZANAHORIA","PATATA","TOMATE","CEBOLLA","AJO","PAN","ARROZ","LECHE","TÉ","CAFÉ","CABALLO","TIGRE","LEÓN","ÁGUILA","PEZ","BALLENA","CONEJO","ZORRO","OSO","LOBO","PÁJARO","MÚSICA","CANCIÓN","HISTORIA","SUEÑO","ESPERANZA","SONRISA","PAZ","VALIENTE","FELIZ","MUNDO","CIUDAD","ESCUELA","APRENDER","CREAR","GANAR","MONEDA","MAGIA","SECRETO","TESORO","CASTILLO","NUBE","LLUVIA","NIEVE","PRIMAVERA","VERANO","OTOÑO","INVIERNO"],
  fr: ["MOT","CHERCHE","JEU","VOYAGE","ÉNIGME","LIVRE","STYLO","PAPIER","MAISON","FAMILLE","AMI","EAU","FEU","TERRE","VENT","LUMIÈRE","NUIT","MATIN","SOLEIL","LUNE","ÉTOILE","FLEUR","ARBRE","RIVIÈRE","MONTAGNE","FORÊT","MER","ÎLE","JARDIN","POMME","MANGUE","ORANGE","BANANE","CITRON","PÊCHE","RAISIN","CAROTTE","POMMEDETERRE","TOMATE","OIGNON","AIL","PAIN","RIZ","LAIT","THÉ","CAFÉ","CHEVAL","TIGRE","LION","AIGLE","POISSON","BALEINE","LAPIN","RENARD","OURS","LOUP","OISEAU","MUSIQUE","CHANSON","HISTOIRE","RÊVE","ESPOIR","SOURIRE","PAIX","COURAGEUX","HEUREUX","MONDE","VILLE","ÉCOLE","APPRENDRE","CRÉER","GAGNER","PIÈCE","MAGIE","SECRET","TRÉSOR","CHÂTEAU","NUAGE","PLUIE","NEIGE","PRINTEMPS","ÉTÉ","AUTOMNE","HIVER"],
  de: ["WORT","SUCHE","SPIEL","REISE","RÄTSEL","BUCH","STIFT","PAPIER","HAUS","FAMILIE","FREUND","WASSER","FEUER","ERDE","WIND","LICHT","NACHT","MORGEN","SONNE","MOND","STERN","BLUME","BAUM","FLUSS","BERG","WALD","MEER","INSEL","GARTEN","APFEL","MANGO","ORANGE","BANANE","ZITRONE","PFIRSICH","TRAUBE","KAROTTE","KARTOFFEL","TOMATE","ZWIEBEL","KNOBLAUCH","BROT","REIS","MILCH","TEE","KAFFEE","PFERD","TIGER","LÖWE","ADLER","FISCH","WAL","KANINCHEN","FUCHS","BÄR","WOLF","VOGEL","MUSIK","LIED","GESCHICHTE","TRAUM","HOFFNUNG","LÄCHELN","FRIEDEN","MUTIG","GLÜCKLICH","WELT","STADT","SCHULE","LERNEN","ERSCHAFFEN","GEWINNEN","MÜNZE","MAGIE","GEHEIMNIS","SCHATZ","BURG","WOLKE","REGEN","SCHNEE","FRÜHLING","SOMMER","HERBST","WINTER"],
  zh: ["文字","搜索","游戏","旅程","谜题","书本","铅笔","纸张","家庭","朋友","水","火","土地","风","光","夜晚","早晨","太阳","月亮","星星","花朵","树木","河流","山脉","森林","海洋","岛屿","花园","苹果","芒果","橙子","香蕉","柠檬","桃子","葡萄","胡萝卜","土豆","番茄","洋葱","大蒜","面包","米饭","牛奶","茶","咖啡","马","老虎","狮子","鹰","鱼","鲸鱼","兔子","狐狸","熊","狼","鸟","音乐","歌曲","故事","梦想","希望","微笑","和平","勇敢","快乐","世界","城市","学校","学习","创造","胜利","硬币","魔法","秘密","宝藏","城堡","云朵","雨水","雪","春天","夏天","秋天","冬天"],
  ja: ["言葉","検索","ゲーム","旅","パズル","本","鉛筆","紙","家","家族","友達","水","火","土","風","光","夜","朝","太陽","月","星","花","木","川","山","森","海","島","庭","りんご","マンゴー","オレンジ","バナナ","レモン","桃","ぶどう","にんじん","じゃがいも","トマト","玉ねぎ","にんにく","パン","米","牛乳","お茶","コーヒー","馬","虎","ライオン","鷲","魚","鯨","うさぎ","狐","熊","狼","鳥","音楽","歌","物語","夢","希望","笑顔","平和","勇気","幸せ","世界","都市","学校","学ぶ","創造","勝利","コイン","魔法","秘密","宝物","城","雲","雨","雪","春","夏","秋","冬"],
};

export function nativeWordsFor(lang: LangCode): string[] {
  return NATIVE_WORDS[lang] ?? NATIVE_WORDS.en;
}

export function nativeWordCount(lang: LangCode): number {
  return nativeWordsFor(lang).length;
}
