import { createServerFn } from "@tanstack/react-start";
import { getPrisma } from "@/lib/db";
import { authMiddleware } from "@/lib/auth/middleware";
import { ACHIEVEMENTS, achievementProgress } from "@/lib/game/achievements";
import { MISSIONS, periodKey } from "@/lib/game/missions";
import { REWARDS, seasonKey, seasonPoints } from "./seasonRules";
const id=(v:unknown)=>String(v??"").trim().slice(0,80);
const value=(s:Record<string,any>,m:string)=>Number(s?.stats?.[m==="levels"?"levelsCompleted":m==="words"?"wordsFound":"coinsEarned"]??0);
const read=(x:string|null)=>x?JSON.parse(x):null;
async function atomicClaim(userId:string,key:string,mutate:(s:Record<string,any>)=>{reward:number;save:Record<string,any>}){
  const db=getPrisma();
  for(let attempt=0;attempt<3;attempt++) try{return await db.$transaction(async tx=>{const idem=await tx.idempotencyKey.findUnique({where:{userId_key:{userId,key}}});if(idem)return{ok:true as const,reward:Number((idem.responseJson as any)?.reward??0)};const row=await tx.playerSave.findUnique({where:{userId}});const s=read(row?.saveJson??null);if(!s||s._serverVerified!==true)return{ok:false as const,error:"Progress must come from a server-verified gameplay session"};const out=mutate(s);if(row)await tx.playerSave.update({where:{userId},data:{saveJson:JSON.stringify(out.save),revision:{increment:1n}}});else await tx.playerSave.create({data:{userId,saveJson:JSON.stringify(out.save),version:1,revision:1n}});await tx.idempotencyKey.create({data:{userId,key,operation:"reward-claim",responseJson:{reward:out.reward},status:"completed"}});return{ok:true as const,reward:out.reward};},{isolationLevel:"Serializable"});}catch(e:any){if(e?.code!=="P2034"&&e?.code!=="P2002")throw e;}return{ok:false as const,error:"Please retry the reward claim."};
}
export const claimAchievementServer=createServerFn({method:"POST"}).middleware([authMiddleware]).validator((d:{id:string})=>({id:id(d.id)})).handler(async({context,data})=>{const a=ACHIEVEMENTS.find(x=>x.id===data.id);if(!a)return{ok:false as const,error:"Unknown achievement"};return atomicClaim(context.userId,`achievement:${a.id}`,s=>{const c=Array.isArray(s.claimedAchievements)?s.claimedAchievements:[];if(c.includes(a.id))return{reward:0,save:s};if(!achievementProgress(a,s.stats).done)throw Object.assign(new Error("Achievement is not unlocked"),{code:"CLAIM_LOCKED"});s.claimedAchievements=[...c,a.id];s.coins=Number(s.coins??0)+a.reward;s.stats={...s.stats,coinsEarned:Number(s.stats?.coinsEarned??0)+a.reward};return{reward:a.reward,save:s};}).catch(e=>({ok:false as const,error:e?.code==="CLAIM_LOCKED"?"Achievement is not unlocked":"Claim failed"}));});
export const claimMissionServer=createServerFn({method:"POST"}).middleware([authMiddleware]).validator((d:{id:string})=>({id:id(d.id)})).handler(async({context,data})=>{const m=MISSIONS.find(x=>x.id===data.id);if(!m)return{ok:false as const,error:"Unknown mission"};const ck=`${m.id}:${periodKey(m.period)}`;return atomicClaim(context.userId,`mission:${ck}`,s=>{const c=Array.isArray(s.claimedMissions)?s.claimedMissions:[];if(c.includes(ck))return{reward:0,save:s};if(value(s,m.metric)<m.target)throw Object.assign(new Error("Mission is not complete"),{code:"CLAIM_LOCKED"});s.claimedMissions=[...c,ck];s.coins=Number(s.coins??0)+m.reward;s.stats={...s.stats,coinsEarned:Number(s.stats?.coinsEarned??0)+m.reward};return{reward:m.reward,save:s};}).catch(e=>({ok:false as const,error:e?.code==="CLAIM_LOCKED"?"Mission is not complete":"Claim failed"}));});
export const claimSeasonTierServer=createServerFn({method:"POST"}).middleware([authMiddleware]).validator((d:{level:number})=>({level:Math.max(1,Math.min(10,Math.floor(Number(d.level))))})).handler(async({context,data})=>{const reward=REWARDS[data.level-1];const key=`${seasonKey()}:${data.level}`;return atomicClaim(context.userId,`season:${key}`,s=>{const c=Array.isArray(s.claimedSeasonTiers)?s.claimedSeasonTiers:[];if(c.includes(key))return{reward:0,save:s};if(seasonPoints(s)<data.level*100)throw Object.assign(new Error("Season tier is locked"),{code:"CLAIM_LOCKED"});s.claimedSeasonTiers=[...c,key];s.coins=Number(s.coins??0)+reward;s.stats={...s.stats,coinsEarned:Number(s.stats?.coinsEarned??0)+reward};return{reward,save:s};}).catch(e=>({ok:false as const,error:e?.code==="CLAIM_LOCKED"?"Season tier is locked":"Claim failed"}));});
