import { useEffect, useState } from "react";
import { Screen } from "@/components/screens/chrome";
import { listDrafts, newDraft, publishDraft, sanitizeWords, saveDraft, validateCreatorWords, type CreatorDraft } from "@/lib/v24/creator/creatorService";
import { useGame } from "@/lib/store";
import { publishCreatorPuzzle, listMyCreatorPuzzles } from "@/lib/v25/creator/cloud";
import { submitCreatorForReview } from "@/lib/v26/creator/community";
export function CreatorScreen(){
 const go=useGame.getState().go; const [drafts,setDrafts]=useState<CreatorDraft[]>([]); const [title,setTitle]=useState(""); const [category,setCategory]=useState("adventure"); const [raw,setRaw]=useState(""); const [msg,setMsg]=useState("");
 useEffect(()=>{setDrafts(listDrafts()); void listMyCreatorPuzzles().then(r=>{if(r.ok) setMsg(`${r.puzzles.length} cloud-published puzzle(s) loaded.`)}).catch(()=>{});},[]);
 const create=()=>{const words=sanitizeWords(raw);const v=validateCreatorWords(words);setMsg(v.reason);if(!v.ok)return;const d=newDraft(title,words,category);saveDraft(d);setDrafts(listDrafts());setTitle("");setRaw("");setMsg("Draft saved and puzzle-checked.");};
 const publish=async(id:string)=>{if(!publishDraft(id))return; const d=listDrafts().find(x=>x.id===id); if(!d)return; setDrafts(listDrafts()); try { const r=await publishCreatorPuzzle({data:{id:d.id,title:d.title,category:d.category,words:d.words}}); setMsg(r.ok?"Saved locally and submitted for cloud moderation review.":`Local draft saved. Cloud: ${r.error}`); } catch { setMsg("Saved locally. Sign in to submit to cloud moderation."); }};
 return <Screen title="Creator Studio"><div className="grid gap-4"><div className="panel rounded-2xl p-4"><p className="text-sm text-muted">Build your own word-search journey. Drafts are stored offline on this device.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Journey title" className="mt-3 w-full rounded-xl border border-border bg-surface px-3 py-3 text-fg"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category" className="mt-2 w-full rounded-xl border border-border bg-surface px-3 py-3 text-fg"/><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="One word per line (3–14 letters)" rows={7} className="mt-2 w-full rounded-xl border border-border bg-surface px-3 py-3 text-fg"/><button onClick={create} className="hud-chip mt-3 text-fg">Validate & Save Draft</button>{msg&&<p className="mt-2 text-sm text-muted">{msg}</p>}</div><div className="grid gap-3">{drafts.map(d=><div key={d.id} className="panel rounded-2xl p-4"><div className="flex items-center justify-between"><b className="text-fg">{d.title}</b><span className="text-xs text-muted">{d.status}</span></div><p className="mt-1 text-xs text-muted">{d.words.length} words · {d.category}</p>{d.status==="draft"&&<button onClick={()=>publish(d.id)} className="hud-chip mt-2 text-fg">Publish</button>}
{d.status==="published"&&<button onClick={async()=>{try{const r=await submitCreatorForReview({data:{id:d.id}});setMsg(r.ok?"Submitted for moderation review.":"Could not submit for review.");}catch{setMsg("Sign in to submit for moderation.");}}} className="hud-chip mt-2 ml-2 text-fg">Submit for Review</button>}</div>)}{!drafts.length&&<p className="text-muted">No creator drafts yet.</p>}</div><button onClick={()=>go("creatorCommunity")} className="text-sm text-primary">Browse Creator Community</button><button onClick={()=>go("more")} className="text-sm text-muted">Back to More</button></div></Screen>;
}
